services:
  quarkus:
    image: ghcr.io/derkoe/java-realworld-example-app:quarkus-main
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/realworld
      QUARKUS_DATASOURCE_USERNAME: realworld
      QUARKUS_DATASOURCE_PASSWORD: password
    depends_on:
      - database
    ports:
      - 8080:8080
  spring-boot:
    image: ghcr.io/derkoe/java-realworld-example-app:spring-boot-main
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/realworld
      SPRING_DATASOURCE_USERNAME: realworld
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database
    ports:
      - 8080:8080
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: password
