realworld:
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtd8RscFhW3haSIHV9fnC
      JeL2k8NIf7kFlURx677FqV65gAaBUus2+ogBhhmmKgJ1mYdKU7oOttfWKdK7Lq3+
      3KFeWs8ASZbnRJiVrZ3ZcvgZpd55Te14CTRVSAVkDPL9EAp/OYlHZI1K+p6FZyIs
      UPH4c9NP8ueRT8NTC+IVMALL9x3im1S4JRwfYOezOFYnFziwB8PXngNuEOuAnexa
      0TEijwbbHB8MPwnrY2snGHN2wMm6ufyAZs2NklLZSjU9SyvAwmVtw0kqPYERZeB7
      AjxQLwAM9+x4GPyny6BXUDV9w4ox/5JHWvpnMiEPAHVO4532WPrlH+YlZrVzOCrY
      vwIDAQAB
      -----END PUBLIC KEY-----
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC13xGxwWFbeFpI
      gdX1+cIl4vaTw0h/uQWVRHHrvsWpXrmABoFS6zb6iAGGGaYqAnWZh0pTug6219Yp
      0rsurf7coV5azwBJludEmJWtndly+Bml3nlN7XgJNFVIBWQM8v0QCn85iUdkjUr6
      noVnIixQ8fhz00/y55FPw1ML4hUwAsv3HeKbVLglHB9g57M4VicXOLAHw9eeA24Q
      64Cd7FrRMSKPBtscHww/CetjaycYc3bAybq5/IBmzY2SUtlKNT1LK8DCZW3DSSo9
      gRFl4HsCPFAvAAz37HgY/KfLoFdQNX3DijH/kkda+mcyIQ8AdU7jnfZY+uUf5iVm
      tXM4Kti/AgMBAAECggEASvjRynz1LUfHr+wVz3hN2GBfVTpDQKN88bNtYskZomAy
      B9ymow/jchNuzWD1Zovs/oUO1sT0G9uNpWABWZTQYxMCWlzKuYtDeruLuC5B3Wr4
      5692QfGKcgDoxu+x9sSUHXC2UXmNvJ2iMv318DXeHuAgk16grnlXJZJXQabJJSjQ
      E3OOFNcFfCRsu/7pj1a7UsnTAaT37xhvxSAFSdoLoWW0G29hJD4Nh2TH85/G/nJ3
      YAIhuudaCYiq0bqBXtbg+eao3HDF59Tmg8jWLoIpaDBvKpxzEOpS8DvfXj2ZUsk5
      ApB7hFys30kOMaEkq6LBcPTlNdIIk/tVAKrg07KHgQKBgQDZ+EFPA1FacyQVS9NW
      mflv/am6v33iOmTRteetgtaApp8PKDjmF8b6e36OXy1+ZCSVWGV0SLuamCJQnPb9
      8DkkeQCqcgyEQyh8s6GvjFU5Sbh3wzX2uml71WsErv7j2dDSOIbPEYL+E9ciRjJY
      F6ggNI36w35DSwwuvJFxCZ65pwKBgQDVmnV2717EYjOw7e25MggDf7KIUJy+Fl5p
      vVaootykT40/b0MJEkzVS0rvBFG5GG9sHGs7oU4KkLWBsU8+V7VLh0ZGktCDYgF2
      CplRZ+f4Km91naLXRQqRRrAw7TRLDcFr+x4WsrN47EPQdOwAZZXLkapEaJ3GY6J2
      qiRMLtGbKQKBgQCyz4CsE/myLNDGE60s1yWUpNCPXbYkV2kLzKFhavsTER1dLs72
      mzzlkVex7gyBKiAE0D5yVZRpbzJ/VTUd/uqxq/5K1ULFYd6d5jLWs1XaqEqHHQJx
      BF2yc9LWRcTeIHq5ahvVVPVT/+y1tkZolAedW9+5fpRfGfrFgHYD+DNY8wKBgF2V
      a4ttOl7eC3mj9HgkFGC8DNMuRk397OV038fIetS+ScsWCw+pZeI5N55ajReEPiTm
      mpCojlGQrwUgUvCkaripjr+SySoWwT8fS6bf2EDhDq5AHz0jcYrOppj5A+UyJKET
      h044gusi0F8/KrrNxwBGVIveLenicyZ8SqTaCllpAoGBAMFN4/2KToEgwH67Isie
      YzsjrkTy8MRoZu+Ks4JyA1/AOW3jfNlmBFBqVSactg10tcqExgpezFNCxUp3YxvZ
      RM3HLtJI2896tq+ODCgCbuDhHYQ3BTWIFIHF97/kN5TNRvyhcicU2L7DkDuByg/i
      Cj9lDYSS1N/7AQe1qmBCqKST
      -----END PRIVATE KEY-----
