name: Build Spring Boot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build native image
        run: |
          mvn -B install
          mvn -B spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/derkoe/java-realworld-example-app:spring-boot-${GITHUB_REF:11} -pl :realworld-example-app-spring-boot
      - name: Push image to ghcr.io
        if: ${{ github.event_name != 'pull_request'}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/derkoe/java-realworld-example-app:spring-boot-${GITHUB_REF:11}
