name: Build Quarkus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Docker login
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build native
        run: |
          mvn -B install
          mvn -B package -Pnative -pl :realworld-example-app-quarkus
      - name: Build Native Image
        if: ${{ github.event_name != 'pull_request'}}
        run: docker build -f quarkus/src/main/docker/Dockerfile.native -t ghcr.io/derkoe/java-realworld-example-app:quarkus-${GITHUB_REF:11} quarkus
      - name: Push image to ghcr.io
        if: ${{ github.event_name != 'pull_request'}}
        run: docker push ghcr.io/derkoe/java-realworld-example-app:quarkus-${GITHUB_REF:11}
