name: Build Quarkus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build
        run: mvn -B install
      - name: Build image
        run: docker build -f quarkus/src/main/docker/Dockerfile.jvm -t ghcr.io/derkoe/java-realworld-example-app:quarkus quarkus
      - name: Build native image
        run: |
          mvn -B package -Pnative -pl :realworld-example-app-quarkus
          docker build -f quarkus/src/main/docker/Dockerfile.native -t ghcr.io/derkoe/java-realworld-example-app:quarkus-native quarkus
      - name: Push images to ghcr.io
        if: ${{ github.event_name != 'pull_request'}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/derkoe/java-realworld-example-app:quarkus
          docker push ghcr.io/derkoe/java-realworld-example-app:quarkus-native
